subdir_files = \
  figures/scd_plotohbands_ir.pdf \
  figures/refl_buttons.eps \
  figures/scd_ploto2a01band.pdf \
  figures/scr_comp_sinfo_H_ex1.pdf \
  figures/TEST-FORS-4_fit.pdf \
  figures/scd_ploto2b01band.pdf \
  figures/refl_buttons.psd \
  figures/TEST-FORS-4-NC_fit.pdf \
  figures/scd_plotohband.pdf \
  figures/run_button.eps \
  figures/N4594-SINFO-J_comp.eps \
  figures/TEST-SINFO-J_with_lines.pdf \
  figures/scd_illlineflags.pdf \
  figures/TEST-SINFO-J_comp.eps \
  figures/varclasses.eps \
  figures/TEST-SINFO-H_fit.pdf \
  figures/N4594-FORS_overplot_w_gal.pdf \
  figures/N4625-FORS_overplot_w_gal.pdf \
  figures/X-Shooter_spec_deriv_1_6-1_605.pdf \
  figures/TEST-SINFO-H_comp.eps \
  figures/N4594-SINFO-H_overplot_w_gal.pdf \
  figures/TEST-XSHOO-1_fit.pdf \
  figures/scd_ploto2a00band.pdf \
  figures/N4625-SINFO-H_with_lines.pdf \
  figures/smd2_logcomp.pdf \
  figures/scd_plotohbands_opt.pdf \
  figures/scr_comp_sinfo_HK_ex1.pdf \
  figures/N4594-SINFO-J_overplot_w_gal.pdf \
  figures/skycorr_gui.png \
  figures/TEST-FORS-1_fit.pdf \
  figures/TEST-SINFO-J_fit.pdf \
  figures/scd_illfeatvar.pdf \
  figures/skycorr_workflow_scheme.png \
  figures/skycorr_reflex.png \
  figures/TEST-SINFO-K_fit.pdf \
  figures/scr_comp_sinfo_K_ex1.pdf
